compress_video fixes and raise compression errors
learningequality/pressurecooker pull request #12
Opened 2018-04-06 01:12 UTC by ivanistheone

This PR makes `compress_video` scale logic more robust. Previously, it was possible to specify a invalid value of `max_width` (e.g. an odd value, or width value that produces an odd height if we keep the same aspect ratio).  (see https://github.com/learningequality/pressurecooker/issues/11)

Other stuff in here:
  - fixed tests
  - added requirements.py and and updated reqs in setup.py
  - added max_height kwarg option that works the same as max_width

## NEW NEW API change NEW NEW
Previously when ffmpeg call inside `compress_video` would fail, an empty file would be produced, which causes downsteam errors in content import (e.g. ricecooker erros our when tries to enerate thumbnail form an invalid video file). To avoid these "silent" errors, we `compress_video` will shoud loudly.... by raising an `VideoCompressionError`

Impact of this API change on Ricecooker:
  - `ricecooker` will be updated to skip file if `VideoCompressionError` and continue operation, but keep track in FAILED_FILES as usual

Impact of this API change on Studio:
  - `compress_video` is used in `compress_nodes` on Studio, but currently `compress_nodes` is not called anywhere, so no impact

Is pressurecooker used elsewhere?

2018-04-06 23:02 UTC, jayoshih approved these changes
Looks good! Pressurecooker is also used in Studio for the thumbnails/encoding code. Eventually, we would like to add more support around video compression, but that hasn't been implemented yet

2018-04-11 15:03 UTC, dragondave commented
Looks good with the sous-chef that had problems with re-encoding. Tests look good on both Python 2 and 3 on Linux.

2018-04-12 15:16 UTC, dragondave commented
The tests don't currently work on Windows for annoying compatibility reasons with NamedTemporaryFile:

https://docs.python.org/2/library/tempfile.html#tempfile.NamedTemporaryFile
> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).

This means that we can't invoke ffmpeg whilst either the input or output file handle is open.
It's OK, we don't need them open, we can close the file handle; but that triggers immediate deletion of the file:
> If delete is true (the default), the file is deleted as soon as it is closed.

So I've wound up writing a wrapper for NamedTemporaryFile which deletes the files when the program terminates instead. I had hoped to just use it on Windows but since NamedTemporaryFile doesn't have a concept of "between closing the filehandle and deleting the file" it's not quite a plug in replacement so it does change the tests a bit.

There's probably a more elegant way of doing this, but I haven't found it yet.

Gist of replacement test_videos.py
https://gist.github.com/dragondave/33148cabb41c72f54ff2885e43f36ae9

2018-04-12 15:17 UTC, dragondave requested changes
See discussion above -- although it's only test-related, so I'm OK for it to go ahead. 
https://gist.github.com/dragondave/33148cabb41c72f54ff2885e43f36ae9

2018-04-12 15:38 UTC, dragondave commented
It may also be useful for future debugging if `videos.py` prints the ffmpeg error message:

```
command = ["ffmpeg", "-y" if overwrite else "-n", "-i", source_file_path, "-profile:v", "baseline",
           "-level", "3.0", "-b:a", "32k", "-ac", "1", "-vf", "scale={}".format(scale),
           "-crf", str(crf), "-preset", "slow", "-v", "error", "-strict", "-2", "-stats", target_file]
try:
    subprocess.check_output(command, stderr=subprocess.STDOUT)
except subprocess.CalledProcessError as e:
    raise VideoCompressionError("{}: {}".format(e, e.output))
```

(I haven't tested this at length, but it appears to give reasonable error messages for the few things I've tried.)

2018-04-16 19:54 UTC, merged